### ISSUE TITLE
flexible table formatting

### ISSUE THREAD

**Issue by d-led** [r-lyeh/dollar#1]
a superb tool, thanks for open-sourcing!

The issue:
I've added a loop in the sample main around the call to `a`, and noticed, that the table has a fixed width formatting:

```
------+-------+-------+-------+-----+-------------
  min |   avg |   max |     % |   # | scope
------+-------+-------+-------+-----+-------------
 0.00 |  0.00 |  0.00 |  0.00 |   3 | main(sample.cc:26)
 0.00 |  0.00 |  0.00 |  0.00 |   3 |  a(sample.cc:18)
15.82 | 15.82 | 15.82 | 15.82 |  30 |   a(sample.cc:19)
 0.00 |  0.00 |  0.00 |  0.00 |  30 |    b(sample.cc:12)
76.23 | 76.23 | 76.23 | 76.23 | 135 |     b(sample.cc:13)
 0.00 |  0.00 |  0.00 |  0.00 | 135 |      c(sample.cc:6)
192.96 | 192.96 | 192.96 | 192.96 | 360 |       c(sample.cc:8)
```

Some time ago I've been fiddling around with automatic formatting of fixed-width-console outputs: http://ideone.com/k7Jcfy

It's been originally inspired by [bettyprint](https://github.com/dattanchu/bprinter)

Please feel free to dissect and use.

The header coloring placeholder is for a RAII wrapper around [rlutil](https://github.com/tapio/rlutil)

**Comment by r-lyeh-archived** [comment]
hey @d-led. yep i forgot to add this enhacement in the todo list. it's definitely a worthy addon (although the code is so tweakable that maybe the new additions are going to be much bigger than the string modification itself). i have some flexible formatter around somewhere that i might use, or just use your link, or just wait for someone to send a PR in between. leaving this open for now... : ) thx

**Comment by d-led** [comment]
:+1:

**Comment by r-lyeh-archived** [comment]
that ascii printer is just so cool btw. neat

**Comment by d-led** [comment]
thanks

**Comment by d-led** [comment]
does that look ok?
d-led/profit@9335dd121569dc813d250b6e416462477d4679c2

```
+----------------------------------------------------------------------+
|   min |   avg |   max |     % |   # | scope                          |
+----------------------------------------------------------------------+
|  0.00 |  0.00 |  0.00 |  0.00 |   1 | int main()(sample.cc:25)       |
|  0.00 |  0.00 |  0.00 |  0.00 |   1 | void a(int)(sample.cc:18)      |
|  5.90 |  5.90 |  5.90 |  5.90 |  10 |   void a(int)(sample.cc:19)    |
|  0.04 |  0.04 |  0.04 |  0.04 |  10 |    void b(int)(sample.cc:12)   |
| 25.70 | 25.70 | 25.70 | 25.70 |  45 |     void b(int)(sample.cc:13)  |
|  0.15 |  0.15 |  0.15 |  0.15 |  45 |      void c(int)(sample.cc:6)  |
| 68.22 | 68.22 | 68.22 | 68.22 | 120 |       void c(int)(sample.cc:8) |
+----------------------------------------------------------------------+
```

**Comment by r-lyeh-archived** [comment]
@d-led, what's the license for the auto_table class? public domain?

**Comment by d-led** [comment]
yep. That new one of yours looks great! auto_table is also inspired by, but isn't based on [bprinter](https://github.com/dattanchu/bprinter)
